[package]
name = "vx-provider-python"
version.workspace = true
edition.workspace = true
description = "Python provider for vx - using python-build-standalone"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-runtime = { workspace = true }
vx-starlark = { workspace = true }
vx-manifest = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
rstest = { workspace = true }
