[package]
name = "vx-provider-bun"
version.workspace = true
edition.workspace = true
description = "Bun runtime provider for vx"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-runtime = { version = "0.4.0", path = "../../vx-runtime" }
vx-paths = { version = "0.3.1", path = "../../vx-paths" }
serde = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
