[package]
name = "vx-provider-vscode"
version.workspace = true
edition.workspace = true
description = "Visual Studio Code provider for vx"
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
vx-runtime = { workspace = true }
vx-version-fetcher = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
