[package]
name = "vx-provider-pwsh"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
vx-runtime = { workspace = true }
vx-starlark = { workspace = true }
vx-manifest = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[lib]
name = "vx_provider_pwsh"
path = "src/lib.rs"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
